### ISSUE TITLE
mentor notes - questions & things that Akin explained verbally

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/introduction-to-express#1]
Started with Q&A:
+ Tell me a bit about express
+ What's the difference between a library and a framework
+ What's the difference between opinionated and unopinionated?

Then @Akin909
+ cast [the rambda docs](http://ramdajs.com/docs/)
+ @Akin909 cast the node core version and then ["Express hello world"](https://github.com/foundersandcoders/introduction-to-express#express-hello-world) for a direct comparison (this was _hugely_ motivating for students & were really excited to do the code along after seeing this)

**Comment by zurda** [comment]
Is there an action item for this? Happy to help if needed!

**Comment by astroash** [comment]
outdated issue
